module.exports = {
    libraryNotInstalled: `Git Flow library is not installed on your computer. Click install and follow instructions to install it.`,
    libraryInstallUrl: 'https://goo.gl/M2Ai1a',
    firstGFInitQuestion: 'Branch name for production releases: [default is master]',
    secondGFInitQuestion: 'Branch name for "next release" development: [default is develop]',
    thirdGFInitQuestion: 'How to name your feature branches? [default is feature/]',
    fourthGFInitQuestion: 'How to name your bugfix branches? [default is bugfix/]',
    fifthGFInitQuestion: 'How to name your release branches? [default is release/]',
    sixthGFInitQuestion: 'How to name your hotfix branches? [default is hotfix/]',
    seventhGFInitQuestion: 'How to name your support branches? [default is support/]',
    eighthGFInitQuestion: 'How to name your version tag prefix?',
    ninthGFInitQuestion: 'Hooks and filters directory? default is',
    branchStart: 'What is the new {0} branch name that you want to start?',
    branchNameEmptyWarning: 'Branch name can not be an empty string.',
    branchNameExist: "Fatal: Branch {0} already exists. Pick another name.",
    branchCreated: `Branch '{0}' successfully created.`,
    selectBranchFinish: `Select {0} branch to finish.`,
    branchFinished: `Branch '{0}' successfully finished.`,
    dontHaveBranch: 'You do not have {0} branches.',
    feature: 'feature',
    bugfix: 'bugfix',
    release: 'release',
    hotfix: 'hotfix',
    support: 'support',
    existingBranchError: 'There is an existing {0} branch {1}. Finish that one first.',
    optionalSelectedBaseBranch: 'Select one of your branche(s) to basing it. (default is {0})',
    finishTagMessage: 'Write a message for tag.',
    aTagMessageIsMandatory: 'A tag message is mandatory.',
    selectBranchPublish: `Select '{0}' branch to publish.`,
    branchPublished: 'Branch {0} successfully published.',
    publishing: 'Publishing {0}',
    branchPublishStatusBarText: 'Publishing your branch to your remote repository.',
    selectBranchToRename: 'Select one of your {0} branche(s) to rename.',
    newNameForBranch: 'Enter new name for your {0} branch.',
    branchRenamed: `Branch '{0}' successfully renamed to '{1}'.`,
    goToInstall: 'Install',
    selectBranchToDelete: 'Select one of your {0} branche(s) to delete.',
    branchDeleted: `Branch '{0}' successfully deleted.`,
}