module.exports = {
    libraryNotInstalled: `Git Flow library is not installed on your computer. Go to link and follow instructions to install it.`,
    libraryInstallUrl: 'https://goo.gl/M2Ai1a',
    firstGFInitQuestion: 'Branch name for production releases: [default is master]',
    secondGFInitQuestion: 'Branch name for "next release" development: [default is develop]',
    thirdGFInitQuestion: 'How to name your feature branches? [default is feature/]',
    fourthGFInitQuestion: 'How to name your bugfix branches? [default is bugfix/]',
    fifthGFInitQuestion: 'How to name your release branches? [default is release/]',
    sixthGFInitQuestion: 'How to name your hotfix branches? [default is hotfix/]',
    seventhGFInitQuestion: 'How to name your support branches? [default is support/]',
    eighthGFInitQuestion: 'How to name your version tag prefix?',
    ninthGFInitQuestion: 'Hooks and filters directory? default is',
    branchStart: 'What is the new {0} branch name that you want to start?',
    branchNameEmptyWarning: 'Branch name can not be an empty string.',
    branchNameExist: "Fatal: Branch {0} already exists. Pick another name.",
    branchCreated: `Branch '{0}' successfully created.`,
    selectBranch: `Select '{0}' branch to finish.`,
    branchFinished: 'Branch {0} successfully finished.',
    dontHaveBranch: 'You do not have {0} branches.',
    feature: 'feature',
    bugfix: 'bugfix',
    release: 'release',
    hotfix: 'hotfix',
    support: 'support',
    existingReleaseBranchError: 'There is an existing release branch {0}. Finish that one first.',
    optionalSelectedBaseBranch: 'Select one of your branches to basing it. (default is {0})',
}